CREATE TABLE `TM_DEVICE` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CHR_CODE` varchar(64) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`INT_PLANT_ID` bigint unsigned,
	`CHR_KIND` enum('SCANNER','RFID','MACHINE_PANEL','PRINTER') NOT NULL,
	`CHR_TOKEN_HASH` varchar(255),
	`CHR_LAST_SEEN_AT` varchar(32),
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_DEVICE_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_DEVICE_CODE_UNIQUE` UNIQUE(`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_PLANT` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CHR_CODE` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_PLANT_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_PLANT_CODE_UNIQUE` UNIQUE(`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_ROLE` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CHR_NAME` varchar(64) NOT NULL,
	`CHR_LABEL` varchar(128),
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_ROLE_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_ROLE_NAME_UNIQUE` UNIQUE(`CHR_NAME`)
);
--> statement-breakpoint
CREATE TABLE `TM_USER` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CHR_NPK` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`CHR_EMAIL` varchar(191),
	`CHR_PASSWORD_HASH` varchar(255),
	`INT_ROLE_ID` bigint unsigned,
	`INT_PLANT_ID` bigint unsigned,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_USER_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_USER_NPK_UNIQUE` UNIQUE(`CHR_NPK`),
	CONSTRAINT `TM_USER_EMAIL_UNIQUE` UNIQUE(`CHR_EMAIL`)
);
--> statement-breakpoint
CREATE TABLE `TM_SHIPPING_PARTS` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_CUSTOMER_ID` bigint unsigned NOT NULL,
	`CHR_CUS_PART_NO` varchar(64) NOT NULL,
	`CHR_CUS_BACK_NO` varchar(64),
	`INT_QTY_PER_BOX` int,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_SHIPPING_PARTS_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_SHIPPING_PARTS_UNIQUE` UNIQUE(`INT_CUSTOMER_ID`,`CHR_CUS_PART_NO`)
);
--> statement-breakpoint
CREATE TABLE `TM_CUST` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CHR_CUST_NO` varchar(32) NOT NULL,
	`CHR_CUST_NAME` varchar(128) NOT NULL,
	`CHR_DOCK` varchar(32),
	`CHR_PART_NUMBER_FORMAT` enum('TMMIN','SUZUKI','MMKI','TBINA','NONE') NOT NULL DEFAULT 'NONE',
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_CUST_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_CUST_CODE_UNIQUE` UNIQUE(`CHR_CUST_NO`)
);
--> statement-breakpoint
CREATE TABLE `TM_LINE` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_CODE` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING','MACHINING','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY') NOT NULL,
	`INT_INPUT_LOCATION_ID` bigint unsigned,
	`INT_OUTPUT_LOCATION_ID` bigint unsigned,
	`INT_SORT_ORDER` int NOT NULL DEFAULT 0,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_LINE_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_LINE_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_MACHINE` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`CHR_CODE` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`CHR_EXTERNAL_REF` varchar(64),
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_MACHINE_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_MACHINE_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_PROCESS_PARTS` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING','MACHINING','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY') NOT NULL,
	`INT_SEQ_NO` int NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_PROCESS_PARTS_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_PROCESS_PARTS_PART_PROCESS_UNIQUE` UNIQUE(`INT_PART_ID`,`CHR_PROCESS_TYPE`),
	CONSTRAINT `TM_PROCESS_PARTS_PART_SEQ_UNIQUE` UNIQUE(`INT_PART_ID`,`INT_SEQ_NO`)
);
--> statement-breakpoint
CREATE TABLE `TM_PARTS` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`CHR_PART_NO` varchar(64) NOT NULL,
	`CHR_BACK_NO` varchar(64),
	`CHR_PROJECT` varchar(32),
	`CHR_PART_NAME` varchar(191) NOT NULL,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING','MACHINING','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY') NOT NULL,
	`CHR_PART_TYPE` enum('RAW_MATERIAL','COMPONENT','WIP','FINISHED_GOOD') NOT NULL DEFAULT 'FINISHED_GOOD',
	`CHR_SOURCE_TYPE` enum('PURCHASED','MANUFACTURED') NOT NULL DEFAULT 'MANUFACTURED',
	`CHR_TRACKING_MODE` enum('SERIAL','LOT','QUANTITY') NOT NULL DEFAULT 'SERIAL',
	`CHR_PART_UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`INT_QTY_PER_BOX` int,
	`INT_STANDARD_STOCK` int NOT NULL DEFAULT 0,
	`CHR_PHOTO_PATH` varchar(255),
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_PARTS_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_PARTS_PLANT_PARTNUMBER_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_PART_NO`)
);
--> statement-breakpoint
CREATE TABLE `TM_VENDOR` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CHR_SUPPLIER_ID` varchar(32) NOT NULL,
	`CHR_SUPPLIER_NAME` varchar(128) NOT NULL,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_VENDOR_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_VENDOR_CODE_UNIQUE` UNIQUE(`CHR_SUPPLIER_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_TOOLING_PARTS` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_TOOLING_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_TOOLING_PARTS_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_TOOLING_PARTS_UNIQUE` UNIQUE(`INT_TOOLING_ID`,`INT_PART_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_TOOLING` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_CODE` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`CHR_KIND` enum('MOLD','DIES','JIG') NOT NULL,
	`INT_CAVITY` int NOT NULL DEFAULT 1,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_TOOLING_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_TOOLING_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TT_KANBAN_EVENT` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_KANBAN_ID` bigint unsigned NOT NULL,
	`CHR_TYPE` enum('PRODUCED','PULLED','PAIRED','STORED','LOADED','DELIVERED','CANCELLED','ADJUSTED') NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`INT_PAIRED_KANBAN_ID` bigint unsigned,
	`INT_QTY` int,
	`INT_USER_ID` bigint unsigned,
	`INT_DEVICE_ID` bigint unsigned,
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`CHR_META` json,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_KANBAN_EVENT_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_KANBAN` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_CUSTOMER_ID` bigint unsigned,
	`CHR_SERIAL_NUMBER` varchar(64) NOT NULL,
	`INT_QTY` int NOT NULL,
	`CHR_STATUS` enum('CREATED','PRODUCED','STORED','PULLED','LOADED','DELIVERED','CANCELLED') NOT NULL DEFAULT 'CREATED',
	`DTM_PRODUCED_AT` timestamp,
	`DTM_DELIVERED_AT` timestamp,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_KANBAN_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_KANBAN_PLANT_SERIAL_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_SERIAL_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TT_PRODUCTION_PLAN` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_CUSTOMER_ID` bigint unsigned,
	`DTM_PLAN_DATE` date NOT NULL,
	`INT_CYCLE` int NOT NULL DEFAULT 1,
	`INT_SEQ_NO` int NOT NULL DEFAULT 0,
	`INT_ORDER_QTY` int NOT NULL DEFAULT 0,
	`INT_DIRECT_PULLING_QTY` int NOT NULL DEFAULT 0,
	`INT_STOCK_CHUTE_QTY` int NOT NULL DEFAULT 0,
	`CHR_DOCK` varchar(32),
	`CHR_DN_NUMBER` varchar(64),
	`DTM_WORKING_START` time,
	`DTM_WORKING_END` time,
	`DTM_DELIVERY_TIME` time,
	`DTM_ACTUAL_START_AT` timestamp,
	`DTM_ACTUAL_END_AT` timestamp,
	`CHR_PLAN_SOURCE` enum('MANUAL','IMPORT','STATIC_SEQ','API') NOT NULL DEFAULT 'MANUAL',
	`CHR_STATUS` enum('DRAFT','RELEASED','RUNNING','DONE','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_PRODUCTION_PLAN_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_PRODUCTION_PLAN_SLOT_UNIQUE` UNIQUE(`INT_LINE_ID`,`DTM_PLAN_DATE`,`INT_CYCLE`,`INT_SEQ_NO`)
);
--> statement-breakpoint
CREATE TABLE `TT_HISTORY_SCAN` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_KIND` enum('PRODUCTION','PULLING','DELIVERY','RECEIVING','INSPECTION','STOCK_TAKE') NOT NULL,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING','MACHINING','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY'),
	`INT_LINE_ID` bigint unsigned,
	`INT_PART_ID` bigint unsigned,
	`INT_MACHINE_ID` bigint unsigned,
	`INT_PRODUCTION_PLAN_ID` bigint unsigned,
	`CHR_RAW_CODE` varchar(255) NOT NULL,
	`CHR_SERIAL_NUMBER` varchar(64),
	`INT_QTY` int NOT NULL DEFAULT 1,
	`INT_USER_ID` bigint unsigned,
	`INT_DEVICE_ID` bigint unsigned,
	`DTM_SCANNED_AT` timestamp NOT NULL,
	`CHR_DEDUPE_KEY` varchar(128) NOT NULL,
	`CHR_META` json,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_HISTORY_SCAN_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_HISTORY_SCAN_DEDUPE_UNIQUE` UNIQUE(`CHR_DEDUPE_KEY`)
);
--> statement-breakpoint
CREATE TABLE `TM_LOCATION` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_CODE` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`CHR_KIND` enum('WAREHOUSE','WIP','FINISH_GOOD','STAGING','CHUTE','NG','TRANSIT') NOT NULL,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_LOCATION_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_LOCATION_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TT_STOCK_MUTATION` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_LOCATION_ID` bigint unsigned,
	`INT_LINE_ID` bigint unsigned,
	`INT_LOT_ID` bigint unsigned,
	`CHR_TYPE` enum('PRODUCTION_IN','DELIVERY_OUT','NG_OUT','ADJUSTMENT','STOCK_TAKE','TRANSFER_IN','TRANSFER_OUT','RECEIVING_IN','CONSUMPTION_OUT') NOT NULL,
	`FLT_QTY` decimal(14,4) NOT NULL,
	`CHR_SOURCE_TABLE` varchar(64),
	`INT_SOURCE_ID` bigint unsigned,
	`CHR_NPK` varchar(32),
	`INT_USER_ID` bigint unsigned,
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`CHR_NOTE` varchar(255),
	`CHR_META` json,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_STOCK_MUTATION_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_STOCK_BALANCE` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_LOCATION_ID` bigint unsigned,
	`DTM_BALANCE_DATE` date NOT NULL,
	`FLT_OPENING_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`FLT_IN_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`FLT_OUT_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`FLT_CLOSING_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_STOCK_BALANCE_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_STOCK_BALANCE_UNIQUE` UNIQUE(`INT_PART_ID`,`INT_LOCATION_ID`,`DTM_BALANCE_DATE`)
);
--> statement-breakpoint
CREATE TABLE `TT_INSPECTION_L` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_INSPECTION_ID` bigint unsigned NOT NULL,
	`INT_NG_MASTER_ID` bigint unsigned NOT NULL,
	`INT_QTY` int NOT NULL DEFAULT 0,
	`CHR_META` json,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_INSPECTION_L_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_NG` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_CODE` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING','MACHINING','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY'),
	`CHR_CATEGORY` varchar(64),
	`INT_SORT_ORDER` int NOT NULL DEFAULT 0,
	`CHR_IS_ACTIVE` enum('0','1') NOT NULL DEFAULT '1',
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_NG_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_NG_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TT_INSPECTION_H` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`INT_MACHINE_ID` bigint unsigned,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING','MACHINING','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY') NOT NULL,
	`DTM_INSPECTED_AT` timestamp NOT NULL,
	`CHR_SHIFT` enum('1','2','3'),
	`INT_CHECKED_QTY` int NOT NULL DEFAULT 0,
	`INT_OK_QTY` int NOT NULL DEFAULT 0,
	`INT_NG_QTY` int NOT NULL DEFAULT 0,
	`INT_INSPECTOR_ID` bigint unsigned,
	`CHR_NOTE` varchar(255),
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_INSPECTION_H_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_DELIVERY` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_CUSTOMER_ID` bigint unsigned NOT NULL,
	`CHR_DEL_NO` varchar(64) NOT NULL,
	`CHR_DOK_NO` varchar(64),
	`CHR_PDS_NO` varchar(64),
	`DTM_DEL_DATE` date NOT NULL,
	`INT_CYCLE` int NOT NULL DEFAULT 1,
	`CHR_CUS_DEST` varchar(32),
	`DTM_PLAN_TIME` time,
	`DTM_DEPARTED_AT` timestamp,
	`DTM_ARRIVED_AT` timestamp,
	`CHR_STATUS` enum('DRAFT','PICKING','PICKED','LOADING','SHIPPED','RECEIVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`INT_LOCATION_ID` bigint unsigned,
	`INT_STAGING_LOCATION_ID` bigint unsigned,
	`CHR_TRUCK_NUMBER` varchar(32),
	`CHR_DRIVER_NAME` varchar(128),
	`CHR_TRUCK_STATUS` enum('PENDING','ARRIVED','LOADING','DEPARTED') NOT NULL DEFAULT 'PENDING',
	`DTM_TRUCK_PICKED_AT` timestamp,
	`INT_TRUCK_PICKED_BY_ID` bigint unsigned,
	`INT_CREATED_BY_ID` bigint unsigned,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_DELIVERY_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_DELIVERY_PLANT_DOCUMENT_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_DEL_NO`)
);
--> statement-breakpoint
CREATE TABLE `TT_DELIVERY_ITEM` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_DELIVERY_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_CUSTOMER_PART_ID` bigint unsigned,
	`INT_PLANNED_KANBAN` int NOT NULL DEFAULT 0,
	`INT_TOTAL_QTY` int NOT NULL DEFAULT 0,
	`INT_QTY_PER_BOX` int NOT NULL DEFAULT 0,
	`INT_PICKED_KANBAN` int NOT NULL DEFAULT 0,
	`INT_SCAN_QTY` int NOT NULL DEFAULT 0,
	`INT_ACTUAL_KANBAN` int NOT NULL DEFAULT 0,
	`INT_ACTUAL_DEL` int NOT NULL DEFAULT 0,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_DELIVERY_ITEM_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_DELIVERY_ITEM_UNIQUE` UNIQUE(`INT_DELIVERY_ID`,`INT_PART_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_MACHINE_EVENT` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_MACHINE_ID` bigint unsigned,
	`CHR_TYPE` enum('SHOT','CYCLE_END','ALARM','DOWNTIME_START','DOWNTIME_END','STATUS_CHANGE','DANDORI_START','DANDORI_END') NOT NULL,
	`CHR_SOURCE` enum('MQTT','J922_SYNC','MANUAL') NOT NULL,
	`CHR_STATUS` varchar(64),
	`INT_SHOT_COUNT` int,
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`CHR_DEDUPE_KEY` varchar(128),
	`CHR_PAYLOAD` json,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_MACHINE_EVENT_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_BOM` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PARENT_PART_ID` bigint unsigned NOT NULL,
	`INT_COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`FLT_QTY_PER` decimal(12,4) NOT NULL,
	`CHR_UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`FLT_SCRAP_PCT` decimal(5,2) NOT NULL DEFAULT '0',
	`INT_SEQUENCE` int NOT NULL DEFAULT 0,
	`DTM_EFFECTIVE_FROM` date NOT NULL,
	`DTM_EFFECTIVE_TO` date,
	`CHR_NOTE` varchar(255),
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_BOM_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_CONSUMPTION` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`INT_PRODUCED_PART_ID` bigint unsigned NOT NULL,
	`INT_COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`INT_LOT_ID` bigint unsigned,
	`FLT_QTY` decimal(14,4) NOT NULL,
	`CHR_UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`CHR_SOURCE` enum('BACKFLUSH','MANUAL','ADJUSTMENT') NOT NULL,
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`INT_USER_ID` bigint unsigned,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_CONSUMPTION_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_GENEALOGY` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_PARENT_SERIAL` varchar(64) NOT NULL,
	`INT_PARENT_PART_ID` bigint unsigned NOT NULL,
	`INT_COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`CHR_COMPONENT_SERIAL` varchar(64),
	`INT_COMPONENT_LOT_ID` bigint unsigned,
	`FLT_QTY` decimal(14,4) NOT NULL DEFAULT '1',
	`CHR_EVIDENCE` enum('SCANNED','INFERRED') NOT NULL DEFAULT 'INFERRED',
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`DTM_SUPERSEDED_AT` timestamp,
	`INT_SUPERSEDED_BY_REPAIR_ID` bigint unsigned,
	`CHR_META` json,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_GENEALOGY_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_LOT` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`CHR_BATCH_NO` varchar(64) NOT NULL,
	`CHR_SUPPLIER_LOT_NUMBER` varchar(64),
	`INT_SUPPLIER_ID` bigint unsigned,
	`DTM_RECEIVED_AT` timestamp,
	`DTM_EXPIRES_AT` date,
	`FLT_INITIAL_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`CHR_STATUS` enum('OPEN','CONSUMED','BLOCKED','RETURNED') NOT NULL DEFAULT 'OPEN',
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_LOT_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_LOT_PLANT_NUMBER_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_BATCH_NO`)
);
--> statement-breakpoint
CREATE TABLE `TT_PURCHASE_RECEIPT_L` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_RECEIPT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_LOT_ID` bigint unsigned,
	`FLT_RECQTY` decimal(14,4) NOT NULL,
	`CHR_UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_PURCHASE_RECEIPT_L_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_PURCHASE_RECEIPT_H` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_SUPPLIER_ID` bigint unsigned NOT NULL,
	`CHR_PDS_NO` varchar(64) NOT NULL,
	`CHR_SUPPLIER_DOC_NUMBER` varchar(64),
	`DTM_RECEIVED_AT` timestamp NOT NULL,
	`INT_LOCATION_ID` bigint unsigned,
	`CHR_STATUS` enum('DRAFT','RECEIVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`INT_RECEIVED_BY_ID` bigint unsigned,
	`CHR_NOTE` varchar(255),
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_PURCHASE_RECEIPT_H_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_PURCHASE_RECEIPT_H_PLANT_DOCUMENT_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_PDS_NO`)
);
--> statement-breakpoint
CREATE TABLE `TT_GOODS_MOVEMENT_L` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_TRANSFER_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_LOT_ID` bigint unsigned,
	`CHR_SERIAL_NUMBER` varchar(64),
	`FLT_TOTAL_QTY` decimal(14,4) NOT NULL,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_GOODS_MOVEMENT_L_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_GOODS_MOVEMENT_H` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_NUMBER` varchar(64) NOT NULL,
	`INT_FROM_LOCATION_ID` bigint unsigned,
	`INT_TO_LOCATION_ID` bigint unsigned,
	`INT_FROM_LINE_ID` bigint unsigned,
	`INT_TO_LINE_ID` bigint unsigned,
	`DTM_MOVED_AT` timestamp NOT NULL,
	`CHR_STATUS` enum('DRAFT','MOVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`INT_USER_ID` bigint unsigned,
	`CHR_NOTE` varchar(255),
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_GOODS_MOVEMENT_H_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_GOODS_MOVEMENT_H_PLANT_DOCUMENT_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TT_NG_DISPOSITION` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`CHR_SERIAL_NUMBER` varchar(64),
	`INT_LOT_ID` bigint unsigned,
	`FLT_QTY` decimal(14,4) NOT NULL,
	`CHR_DISPOSITION` enum('REMELT','REPAIR','DISCARD','RETURN_SUPPLIER') NOT NULL,
	`INT_CONVERTED_TO_PART_ID` bigint unsigned,
	`FLT_CONVERTED_QTY` decimal(14,4),
	`INT_CONVERTED_LOT_ID` bigint unsigned,
	`CHR_REASON` varchar(255),
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`INT_USER_ID` bigint unsigned,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_NG_DISPOSITION_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_REPAIR_L` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_REPAIR_ID` bigint unsigned NOT NULL,
	`INT_COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`CHR_REMOVED_SERIAL` varchar(64),
	`INT_REMOVED_LOT_ID` bigint unsigned,
	`CHR_REMOVED_DISPOSITION` enum('REMELT','REPAIR','DISCARD','RETURN_SUPPLIER'),
	`CHR_INSTALLED_SERIAL` varchar(64),
	`INT_INSTALLED_LOT_ID` bigint unsigned,
	`FLT_QTY` decimal(14,4) NOT NULL DEFAULT '1',
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_REPAIR_L_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_REPAIR_H` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`CHR_SERIAL_NUMBER` varchar(64) NOT NULL,
	`CHR_REASON` varchar(255),
	`CHR_STATUS` enum('OPEN','DONE','SCRAPPED') NOT NULL DEFAULT 'OPEN',
	`DTM_STARTED_AT` timestamp NOT NULL,
	`DTM_FINISHED_AT` timestamp,
	`INT_USER_ID` bigint unsigned,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_REPAIR_H_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_SCRAP_RULE` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`CHR_DISPOSITION` enum('REMELT','REPAIR','DISCARD','RETURN_SUPPLIER') NOT NULL,
	`INT_CONVERTS_TO_PART_ID` bigint unsigned,
	`FLT_CONVERSION_QTY` decimal(12,4),
	`CHR_CONVERSION_UOM` varchar(16),
	`CHR_NOTE` varchar(255),
	`CHR_IS_ACTIVE` enum('0','1') NOT NULL DEFAULT '1',
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_SCRAP_RULE_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_SCRAP_RULE_PART_UNIQUE` UNIQUE(`INT_PLANT_ID`,`INT_PART_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_SAP_OUTBOX` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_SOURCE_TABLE` varchar(64) NOT NULL,
	`INT_SOURCE_ID` bigint unsigned NOT NULL,
	`CHR_DOC_TYPE` varchar(32) NOT NULL,
	`CHR_MOVEMENT_TYPE` varchar(8),
	`CHR_IDEMPOTENCY_KEY` varchar(128) NOT NULL,
	`CHR_PAYLOAD` json NOT NULL,
	`CHR_STATUS` enum('PENDING','SENT','CONFIRMED','REJECTED','FAILED','HELD','SKIPPED') NOT NULL DEFAULT 'PENDING',
	`INT_ATTEMPTS` int NOT NULL DEFAULT 0,
	`CHR_LAST_ERROR` varchar(1000),
	`CHR_SAP_DOC_NUMBER` varchar(32),
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`DTM_SENT_AT` timestamp,
	`DTM_CONFIRMED_AT` timestamp,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_SAP_OUTBOX_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_SAP_OUTBOX_SOURCE_UNIQUE` UNIQUE(`CHR_SOURCE_TABLE`,`INT_SOURCE_ID`,`CHR_DOC_TYPE`),
	CONSTRAINT `TT_SAP_OUTBOX_IDEMPOTENCY_UNIQUE` UNIQUE(`CHR_IDEMPOTENCY_KEY`)
);
--> statement-breakpoint
ALTER TABLE `TM_DEVICE` ADD CONSTRAINT `TM_DEVICE_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_USER` ADD CONSTRAINT `TM_USER_INT_ROLE_ID_TM_ROLE_INT_ID_fk` FOREIGN KEY (`INT_ROLE_ID`) REFERENCES `TM_ROLE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_USER` ADD CONSTRAINT `TM_USER_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SHIPPING_PARTS` ADD CONSTRAINT `TM_SHIPPING_PARTS_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SHIPPING_PARTS` ADD CONSTRAINT `TM_SHIPPING_PARTS_INT_CUSTOMER_ID_TM_CUST_INT_ID_fk` FOREIGN KEY (`INT_CUSTOMER_ID`) REFERENCES `TM_CUST`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_LINE` ADD CONSTRAINT `TM_LINE_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_MACHINE` ADD CONSTRAINT `TM_MACHINE_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_MACHINE` ADD CONSTRAINT `TM_MACHINE_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` ADD CONSTRAINT `TM_PROCESS_PARTS_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` ADD CONSTRAINT `TM_PROCESS_PARTS_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` ADD CONSTRAINT `TM_PROCESS_PARTS_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PARTS` ADD CONSTRAINT `TM_PARTS_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PARTS` ADD CONSTRAINT `TM_PARTS_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_TOOLING_PARTS` ADD CONSTRAINT `TM_TOOLING_PARTS_INT_TOOLING_ID_TM_TOOLING_INT_ID_fk` FOREIGN KEY (`INT_TOOLING_ID`) REFERENCES `TM_TOOLING`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_TOOLING_PARTS` ADD CONSTRAINT `TM_TOOLING_PARTS_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_TOOLING` ADD CONSTRAINT `TM_TOOLING_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_INT_KANBAN_ID_TM_KANBAN_INT_ID_fk` FOREIGN KEY (`INT_KANBAN_ID`) REFERENCES `TM_KANBAN`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_INT_DEVICE_ID_TM_DEVICE_INT_ID_fk` FOREIGN KEY (`INT_DEVICE_ID`) REFERENCES `TM_DEVICE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_KANBAN` ADD CONSTRAINT `TM_KANBAN_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_KANBAN` ADD CONSTRAINT `TM_KANBAN_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_KANBAN` ADD CONSTRAINT `TM_KANBAN_INT_CUSTOMER_ID_TM_CUST_INT_ID_fk` FOREIGN KEY (`INT_CUSTOMER_ID`) REFERENCES `TM_CUST`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_INT_CUSTOMER_ID_TM_CUST_INT_ID_fk` FOREIGN KEY (`INT_CUSTOMER_ID`) REFERENCES `TM_CUST`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_INT_MACHINE_ID_TM_MACHINE_INT_ID_fk` FOREIGN KEY (`INT_MACHINE_ID`) REFERENCES `TM_MACHINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_INT_DEVICE_ID_TM_DEVICE_INT_ID_fk` FOREIGN KEY (`INT_DEVICE_ID`) REFERENCES `TM_DEVICE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_PROD_PLAN_FK` FOREIGN KEY (`INT_PRODUCTION_PLAN_ID`) REFERENCES `TT_PRODUCTION_PLAN`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_LOCATION` ADD CONSTRAINT `TM_LOCATION_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_INT_LOCATION_ID_TM_LOCATION_INT_ID_fk` FOREIGN KEY (`INT_LOCATION_ID`) REFERENCES `TM_LOCATION`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_BALANCE` ADD CONSTRAINT `TT_STOCK_BALANCE_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_BALANCE` ADD CONSTRAINT `TT_STOCK_BALANCE_INT_LOCATION_ID_TM_LOCATION_INT_ID_fk` FOREIGN KEY (`INT_LOCATION_ID`) REFERENCES `TM_LOCATION`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_L` ADD CONSTRAINT `TT_INSPECTION_L_INT_INSPECTION_ID_TT_INSPECTION_H_INT_ID_fk` FOREIGN KEY (`INT_INSPECTION_ID`) REFERENCES `TT_INSPECTION_H`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_L` ADD CONSTRAINT `TT_INSPECTION_L_INT_NG_MASTER_ID_TM_NG_INT_ID_fk` FOREIGN KEY (`INT_NG_MASTER_ID`) REFERENCES `TM_NG`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_NG` ADD CONSTRAINT `TM_NG_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_INT_MACHINE_ID_TM_MACHINE_INT_ID_fk` FOREIGN KEY (`INT_MACHINE_ID`) REFERENCES `TM_MACHINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_INT_INSPECTOR_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_INSPECTOR_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_INT_CUSTOMER_ID_TM_CUST_INT_ID_fk` FOREIGN KEY (`INT_CUSTOMER_ID`) REFERENCES `TM_CUST`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_INT_LOCATION_ID_TM_LOCATION_INT_ID_fk` FOREIGN KEY (`INT_LOCATION_ID`) REFERENCES `TM_LOCATION`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_INT_TRUCK_PICKED_BY_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_TRUCK_PICKED_BY_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_INT_CREATED_BY_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_CREATED_BY_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY_ITEM` ADD CONSTRAINT `TT_DELIVERY_ITEM_INT_DELIVERY_ID_TT_DELIVERY_INT_ID_fk` FOREIGN KEY (`INT_DELIVERY_ID`) REFERENCES `TT_DELIVERY`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY_ITEM` ADD CONSTRAINT `TT_DELIVERY_ITEM_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_MACHINE_EVENT` ADD CONSTRAINT `TT_MACHINE_EVENT_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_MACHINE_EVENT` ADD CONSTRAINT `TT_MACHINE_EVENT_INT_MACHINE_ID_TM_MACHINE_INT_ID_fk` FOREIGN KEY (`INT_MACHINE_ID`) REFERENCES `TM_MACHINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_BOM` ADD CONSTRAINT `TM_BOM_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_BOM` ADD CONSTRAINT `TM_BOM_INT_PARENT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PARENT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_BOM` ADD CONSTRAINT `TM_BOM_INT_COMPONENT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_INT_PRODUCED_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PRODUCED_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_INT_COMPONENT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_INT_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_INT_PARENT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PARENT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_INT_COMPONENT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_INT_COMPONENT_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_COMPONENT_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LOT` ADD CONSTRAINT `TT_LOT_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LOT` ADD CONSTRAINT `TT_LOT_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LOT` ADD CONSTRAINT `TT_LOT_INT_SUPPLIER_ID_TM_VENDOR_INT_ID_fk` FOREIGN KEY (`INT_SUPPLIER_ID`) REFERENCES `TM_VENDOR`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_L` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_L_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_L` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_L_INT_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_L` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_L_RECEIPT_FK` FOREIGN KEY (`INT_RECEIPT_ID`) REFERENCES `TT_PURCHASE_RECEIPT_H`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_INT_SUPPLIER_ID_TM_VENDOR_INT_ID_fk` FOREIGN KEY (`INT_SUPPLIER_ID`) REFERENCES `TM_VENDOR`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_INT_LOCATION_ID_TM_LOCATION_INT_ID_fk` FOREIGN KEY (`INT_LOCATION_ID`) REFERENCES `TM_LOCATION`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_INT_RECEIVED_BY_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_RECEIVED_BY_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_L` ADD CONSTRAINT `TT_GOODS_MOVEMENT_L_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_L` ADD CONSTRAINT `TT_GOODS_MOVEMENT_L_INT_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_L` ADD CONSTRAINT `TT_GOODS_MOVEMENT_L_TRANSFER_FK` FOREIGN KEY (`INT_TRANSFER_ID`) REFERENCES `TT_GOODS_MOVEMENT_H`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_INT_FROM_LOCATION_ID_TM_LOCATION_INT_ID_fk` FOREIGN KEY (`INT_FROM_LOCATION_ID`) REFERENCES `TM_LOCATION`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_INT_TO_LOCATION_ID_TM_LOCATION_INT_ID_fk` FOREIGN KEY (`INT_TO_LOCATION_ID`) REFERENCES `TM_LOCATION`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_INT_FROM_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_FROM_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_INT_TO_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_TO_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_INT_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_INT_CONVERTED_TO_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_CONVERTED_TO_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_INT_CONVERTED_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_CONVERTED_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_INT_REPAIR_ID_TT_REPAIR_H_INT_ID_fk` FOREIGN KEY (`INT_REPAIR_ID`) REFERENCES `TT_REPAIR_H`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_INT_COMPONENT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_INT_REMOVED_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_REMOVED_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_INT_INSTALLED_LOT_ID_TT_LOT_INT_ID_fk` FOREIGN KEY (`INT_INSTALLED_LOT_ID`) REFERENCES `TT_LOT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SCRAP_RULE` ADD CONSTRAINT `TM_SCRAP_RULE_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SCRAP_RULE` ADD CONSTRAINT `TM_SCRAP_RULE_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SCRAP_RULE` ADD CONSTRAINT `TM_SCRAP_RULE_INT_CONVERTS_TO_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_CONVERTS_TO_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_SAP_OUTBOX` ADD CONSTRAINT `TT_SAP_OUTBOX_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `TM_DEVICE_PLANT_IDX` ON `TM_DEVICE` (`INT_PLANT_ID`);--> statement-breakpoint
CREATE INDEX `TM_USER_PLANT_IDX` ON `TM_USER` (`INT_PLANT_ID`);--> statement-breakpoint
CREATE INDEX `TM_SHIPPING_PARTS_PART_IDX` ON `TM_SHIPPING_PARTS` (`INT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TM_LINE_PROCESS_IDX` ON `TM_LINE` (`CHR_PROCESS_TYPE`);--> statement-breakpoint
CREATE INDEX `TM_MACHINE_EXTERNAL_REF_IDX` ON `TM_MACHINE` (`CHR_EXTERNAL_REF`);--> statement-breakpoint
CREATE INDEX `TM_PROCESS_PARTS_PLANT_PROCESS_IDX` ON `TM_PROCESS_PARTS` (`INT_PLANT_ID`,`CHR_PROCESS_TYPE`);--> statement-breakpoint
CREATE INDEX `TM_PARTS_BACK_NUMBER_IDX` ON `TM_PARTS` (`CHR_BACK_NO`);--> statement-breakpoint
CREATE INDEX `TM_PARTS_LINE_IDX` ON `TM_PARTS` (`INT_LINE_ID`);--> statement-breakpoint
CREATE INDEX `TT_KANBAN_EVENT_KANBAN_IDX` ON `TT_KANBAN_EVENT` (`INT_KANBAN_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_KANBAN_EVENT_TYPE_TIME_IDX` ON `TT_KANBAN_EVENT` (`CHR_TYPE`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TM_KANBAN_PART_STATUS_IDX` ON `TM_KANBAN` (`INT_PART_ID`,`CHR_STATUS`);--> statement-breakpoint
CREATE INDEX `TM_KANBAN_STATUS_CREATED_IDX` ON `TM_KANBAN` (`CHR_STATUS`,`DTM_CREATED_AT`);--> statement-breakpoint
CREATE INDEX `TT_PRODUCTION_PLAN_DATE_LINE_IDX` ON `TT_PRODUCTION_PLAN` (`DTM_PLAN_DATE`,`INT_LINE_ID`);--> statement-breakpoint
CREATE INDEX `TT_PRODUCTION_PLAN_PART_DATE_IDX` ON `TT_PRODUCTION_PLAN` (`INT_PART_ID`,`DTM_PLAN_DATE`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_TIME_IDX` ON `TT_HISTORY_SCAN` (`DTM_SCANNED_AT`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_LINE_KIND_TIME_IDX` ON `TT_HISTORY_SCAN` (`INT_LINE_ID`,`CHR_KIND`,`DTM_SCANNED_AT`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_PART_TIME_IDX` ON `TT_HISTORY_SCAN` (`INT_PART_ID`,`DTM_SCANNED_AT`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_SERIAL_IDX` ON `TT_HISTORY_SCAN` (`CHR_SERIAL_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_PART_TIME_IDX` ON `TT_STOCK_MUTATION` (`INT_PART_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_TYPE_TIME_IDX` ON `TT_STOCK_MUTATION` (`CHR_TYPE`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_SOURCE_IDX` ON `TT_STOCK_MUTATION` (`CHR_SOURCE_TABLE`,`INT_SOURCE_ID`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_LOT_IDX` ON `TT_STOCK_MUTATION` (`INT_LOT_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_BALANCE_DATE_IDX` ON `TT_STOCK_BALANCE` (`DTM_BALANCE_DATE`);--> statement-breakpoint
CREATE INDEX `TT_INSPECTION_L_INSPECTION_IDX` ON `TT_INSPECTION_L` (`INT_INSPECTION_ID`);--> statement-breakpoint
CREATE INDEX `TT_INSPECTION_H_PART_TIME_IDX` ON `TT_INSPECTION_H` (`INT_PART_ID`,`DTM_INSPECTED_AT`);--> statement-breakpoint
CREATE INDEX `TT_INSPECTION_H_LINE_TIME_IDX` ON `TT_INSPECTION_H` (`INT_LINE_ID`,`DTM_INSPECTED_AT`);--> statement-breakpoint
CREATE INDEX `TT_DELIVERY_DATE_CUSTOMER_IDX` ON `TT_DELIVERY` (`DTM_DEL_DATE`,`INT_CUSTOMER_ID`);--> statement-breakpoint
CREATE INDEX `TT_DELIVERY_STATUS_IDX` ON `TT_DELIVERY` (`CHR_STATUS`);--> statement-breakpoint
CREATE INDEX `TT_DELIVERY_ITEM_PART_IDX` ON `TT_DELIVERY_ITEM` (`INT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_MACHINE_EVENT_MACHINE_TIME_IDX` ON `TT_MACHINE_EVENT` (`INT_MACHINE_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_MACHINE_EVENT_TYPE_TIME_IDX` ON `TT_MACHINE_EVENT` (`CHR_TYPE`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_MACHINE_EVENT_DEDUPE_IDX` ON `TT_MACHINE_EVENT` (`CHR_DEDUPE_KEY`);--> statement-breakpoint
CREATE INDEX `TM_BOM_PARENT_IDX` ON `TM_BOM` (`INT_PARENT_PART_ID`,`DTM_EFFECTIVE_FROM`);--> statement-breakpoint
CREATE INDEX `TM_BOM_COMPONENT_IDX` ON `TM_BOM` (`INT_COMPONENT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_CONSUMPTION_PRODUCED_IDX` ON `TT_CONSUMPTION` (`INT_PRODUCED_PART_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_CONSUMPTION_COMPONENT_IDX` ON `TT_CONSUMPTION` (`INT_COMPONENT_PART_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_CONSUMPTION_LOT_IDX` ON `TT_CONSUMPTION` (`INT_LOT_ID`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_PARENT_IDX` ON `TT_GENEALOGY` (`CHR_PARENT_SERIAL`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_LOT_IDX` ON `TT_GENEALOGY` (`INT_COMPONENT_LOT_ID`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_COMPONENT_SERIAL_IDX` ON `TT_GENEALOGY` (`CHR_COMPONENT_SERIAL`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_PART_TIME_IDX` ON `TT_GENEALOGY` (`INT_PARENT_PART_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_LOT_PART_IDX` ON `TT_LOT` (`INT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_LOT_SUPPLIER_LOT_IDX` ON `TT_LOT` (`CHR_SUPPLIER_LOT_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_PURCHASE_RECEIPT_L_RECEIPT_IDX` ON `TT_PURCHASE_RECEIPT_L` (`INT_RECEIPT_ID`);--> statement-breakpoint
CREATE INDEX `TT_PURCHASE_RECEIPT_L_PART_IDX` ON `TT_PURCHASE_RECEIPT_L` (`INT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_PURCHASE_RECEIPT_H_SUPPLIER_DATE_IDX` ON `TT_PURCHASE_RECEIPT_H` (`INT_SUPPLIER_ID`,`DTM_RECEIVED_AT`);--> statement-breakpoint
CREATE INDEX `TT_GOODS_MOVEMENT_L_TRANSFER_IDX` ON `TT_GOODS_MOVEMENT_L` (`INT_TRANSFER_ID`);--> statement-breakpoint
CREATE INDEX `TT_GOODS_MOVEMENT_L_PART_IDX` ON `TT_GOODS_MOVEMENT_L` (`INT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_GOODS_MOVEMENT_H_MOVED_IDX` ON `TT_GOODS_MOVEMENT_H` (`DTM_MOVED_AT`);--> statement-breakpoint
CREATE INDEX `TT_NG_DISPOSITION_PART_TIME_IDX` ON `TT_NG_DISPOSITION` (`INT_PART_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_NG_DISPOSITION_SERIAL_IDX` ON `TT_NG_DISPOSITION` (`CHR_SERIAL_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_NG_DISPOSITION_DISPOSITION_IDX` ON `TT_NG_DISPOSITION` (`CHR_DISPOSITION`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_L_REPAIR_IDX` ON `TT_REPAIR_L` (`INT_REPAIR_ID`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_L_COMPONENT_IDX` ON `TT_REPAIR_L` (`INT_COMPONENT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_H_SERIAL_IDX` ON `TT_REPAIR_H` (`CHR_SERIAL_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_H_STATUS_IDX` ON `TT_REPAIR_H` (`CHR_STATUS`,`DTM_STARTED_AT`);--> statement-breakpoint
CREATE INDEX `TT_SAP_OUTBOX_STATUS_IDX` ON `TT_SAP_OUTBOX` (`CHR_STATUS`,`DTM_OCCURRED_AT`);