CREATE TABLE `TM_DEVICE` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CODE` varchar(64) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`PLANT_ID` bigint unsigned,
	`KIND` enum('SCANNER','RFID','MACHINE_PANEL','PRINTER') NOT NULL,
	`TOKEN_HASH` varchar(255),
	`LAST_SEEN_AT` varchar(32),
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_DEVICE_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_DEVICE_CODE_UNIQUE` UNIQUE(`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_PLANT` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_PLANT_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_PLANT_CODE_UNIQUE` UNIQUE(`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_ROLE` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`NAME` varchar(64) NOT NULL,
	`LABEL` varchar(128),
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_ROLE_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_ROLE_NAME_UNIQUE` UNIQUE(`NAME`)
);
--> statement-breakpoint
CREATE TABLE `TM_USER` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`NPK` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`EMAIL` varchar(191),
	`PASSWORD_HASH` varchar(255),
	`ROLE_ID` bigint unsigned,
	`PLANT_ID` bigint unsigned,
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_USER_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_USER_NPK_UNIQUE` UNIQUE(`NPK`),
	CONSTRAINT `TM_USER_EMAIL_UNIQUE` UNIQUE(`EMAIL`)
);
--> statement-breakpoint
CREATE TABLE `TM_SHIPPING_PARTS` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`CUSTOMER_ID` bigint unsigned NOT NULL,
	`CUSTOMER_PART_NUMBER` varchar(64) NOT NULL,
	`CUSTOMER_BACK_NUMBER` varchar(64),
	`QTY_PER_KANBAN` int,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_SHIPPING_PARTS_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_SHIPPING_PARTS_UNIQUE` UNIQUE(`CUSTOMER_ID`,`CUSTOMER_PART_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TM_CUST` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`DOCK` varchar(32),
	`PART_NUMBER_FORMAT` enum('TMMIN','SUZUKI','MMKI','TBINA','NONE') NOT NULL DEFAULT 'NONE',
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_CUST_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_CUST_CODE_UNIQUE` UNIQUE(`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_LINE` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`PROCESS_TYPE` enum('CASTING','MACHINING','ASSEMBLING','INJECTION') NOT NULL,
	`INPUT_LOCATION_ID` bigint unsigned,
	`OUTPUT_LOCATION_ID` bigint unsigned,
	`SORT_ORDER` int NOT NULL DEFAULT 0,
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_LINE_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_LINE_PLANT_CODE_UNIQUE` UNIQUE(`PLANT_ID`,`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_MACHINE` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`LINE_ID` bigint unsigned,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`EXTERNAL_REF` varchar(64),
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_MACHINE_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_MACHINE_PLANT_CODE_UNIQUE` UNIQUE(`PLANT_ID`,`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_PARTS` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`LINE_ID` bigint unsigned,
	`PART_NUMBER` varchar(64) NOT NULL,
	`BACK_NUMBER` varchar(64),
	`NAME` varchar(191) NOT NULL,
	`PROCESS_TYPE` enum('CASTING','MACHINING','ASSEMBLING','INJECTION') NOT NULL,
	`PART_TYPE` enum('RAW_MATERIAL','COMPONENT','WIP','FINISHED_GOOD') NOT NULL DEFAULT 'FINISHED_GOOD',
	`SOURCE_TYPE` enum('PURCHASED','MANUFACTURED') NOT NULL DEFAULT 'MANUFACTURED',
	`TRACKING_MODE` enum('SERIAL','LOT','QUANTITY') NOT NULL DEFAULT 'SERIAL',
	`UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`QTY_PER_KANBAN` int,
	`STANDARD_STOCK` int NOT NULL DEFAULT 0,
	`PHOTO_PATH` varchar(255),
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_PARTS_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_PARTS_PLANT_PARTNUMBER_UNIQUE` UNIQUE(`PLANT_ID`,`PART_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TM_VENDOR` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_VENDOR_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_VENDOR_CODE_UNIQUE` UNIQUE(`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_TOOLING_PARTS` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`TOOLING_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_TOOLING_PARTS_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_TOOLING_PARTS_UNIQUE` UNIQUE(`TOOLING_ID`,`PART_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_TOOLING` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`KIND` enum('MOLD','DIES','JIG') NOT NULL,
	`CAVITY` int NOT NULL DEFAULT 1,
	`IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_TOOLING_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_TOOLING_PLANT_CODE_UNIQUE` UNIQUE(`PLANT_ID`,`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TT_KANBAN_EVENT` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`KANBAN_ID` bigint unsigned NOT NULL,
	`TYPE` enum('PRODUCED','PULLED','PAIRED','STORED','LOADED','DELIVERED','CANCELLED','ADJUSTED') NOT NULL,
	`LINE_ID` bigint unsigned,
	`PAIRED_KANBAN_ID` bigint unsigned,
	`QTY` int,
	`USER_ID` bigint unsigned,
	`DEVICE_ID` bigint unsigned,
	`OCCURRED_AT` timestamp NOT NULL,
	`META` json,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_KANBAN_EVENT_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_KANBAN` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`CUSTOMER_ID` bigint unsigned,
	`SERIAL_NUMBER` varchar(64) NOT NULL,
	`QTY` int NOT NULL,
	`STATUS` enum('CREATED','PRODUCED','STORED','PULLED','LOADED','DELIVERED','CANCELLED') NOT NULL DEFAULT 'CREATED',
	`PRODUCED_AT` timestamp,
	`DELIVERED_AT` timestamp,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_KANBAN_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_KANBAN_PLANT_SERIAL_UNIQUE` UNIQUE(`PLANT_ID`,`SERIAL_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TT_PRODUCTION_PLAN` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`LINE_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`CUSTOMER_ID` bigint unsigned,
	`PLAN_DATE` date NOT NULL,
	`CYCLE` int NOT NULL DEFAULT 1,
	`SEQ_NO` int NOT NULL DEFAULT 0,
	`ORDER_QTY` int NOT NULL DEFAULT 0,
	`DIRECT_PULLING_QTY` int NOT NULL DEFAULT 0,
	`STOCK_CHUTE_QTY` int NOT NULL DEFAULT 0,
	`DOCK` varchar(32),
	`DN_NUMBER` varchar(64),
	`WORKING_START` time,
	`WORKING_END` time,
	`DELIVERY_TIME` time,
	`ACTUAL_START_AT` timestamp,
	`ACTUAL_END_AT` timestamp,
	`PLAN_SOURCE` enum('MANUAL','IMPORT','STATIC_SEQ','API') NOT NULL DEFAULT 'MANUAL',
	`STATUS` enum('DRAFT','RELEASED','RUNNING','DONE','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_PRODUCTION_PLAN_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_PRODUCTION_PLAN_SLOT_UNIQUE` UNIQUE(`LINE_ID`,`PLAN_DATE`,`CYCLE`,`SEQ_NO`)
);
--> statement-breakpoint
CREATE TABLE `TT_HISTORY_SCAN` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`KIND` enum('PRODUCTION','PULLING','DELIVERY','RECEIVING','INSPECTION','STOCK_TAKE') NOT NULL,
	`PROCESS_TYPE` enum('CASTING','MACHINING','ASSEMBLING','INJECTION'),
	`LINE_ID` bigint unsigned,
	`PART_ID` bigint unsigned,
	`MACHINE_ID` bigint unsigned,
	`PRODUCTION_PLAN_ID` bigint unsigned,
	`RAW_CODE` varchar(255) NOT NULL,
	`SERIAL_NUMBER` varchar(64),
	`QTY` int NOT NULL DEFAULT 1,
	`USER_ID` bigint unsigned,
	`DEVICE_ID` bigint unsigned,
	`SCANNED_AT` timestamp NOT NULL,
	`DEDUPE_KEY` varchar(128) NOT NULL,
	`META` json,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_HISTORY_SCAN_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_HISTORY_SCAN_DEDUPE_UNIQUE` UNIQUE(`DEDUPE_KEY`)
);
--> statement-breakpoint
CREATE TABLE `TM_LOCATION` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`KIND` enum('WAREHOUSE','WIP','FINISH_GOOD','STAGING','CHUTE','NG','TRANSIT') NOT NULL,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_LOCATION_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_LOCATION_PLANT_CODE_UNIQUE` UNIQUE(`PLANT_ID`,`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TT_STOCK_MUTATION` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`LOCATION_ID` bigint unsigned,
	`LINE_ID` bigint unsigned,
	`LOT_ID` bigint unsigned,
	`TYPE` enum('PRODUCTION_IN','DELIVERY_OUT','NG_OUT','ADJUSTMENT','STOCK_TAKE','TRANSFER_IN','TRANSFER_OUT','RECEIVING_IN','CONSUMPTION_OUT') NOT NULL,
	`QTY` decimal(14,4) NOT NULL,
	`SOURCE_TABLE` varchar(64),
	`SOURCE_ID` bigint unsigned,
	`NPK` varchar(32),
	`USER_ID` bigint unsigned,
	`OCCURRED_AT` timestamp NOT NULL,
	`NOTE` varchar(255),
	`META` json,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_STOCK_MUTATION_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_STOCK_BALANCE` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`LOCATION_ID` bigint unsigned,
	`BALANCE_DATE` date NOT NULL,
	`OPENING_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`IN_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`OUT_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`CLOSING_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_STOCK_BALANCE_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_STOCK_BALANCE_UNIQUE` UNIQUE(`PART_ID`,`LOCATION_ID`,`BALANCE_DATE`)
);
--> statement-breakpoint
CREATE TABLE `TT_INSPECTION_L` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INSPECTION_ID` bigint unsigned NOT NULL,
	`NG_MASTER_ID` bigint unsigned NOT NULL,
	`QTY` int NOT NULL DEFAULT 0,
	`META` json,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_INSPECTION_L_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_NG` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`CODE` varchar(32) NOT NULL,
	`NAME` varchar(128) NOT NULL,
	`PROCESS_TYPE` enum('CASTING','MACHINING','ASSEMBLING','INJECTION'),
	`CATEGORY` varchar(64),
	`SORT_ORDER` int NOT NULL DEFAULT 0,
	`IS_ACTIVE` enum('0','1') NOT NULL DEFAULT '1',
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_NG_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_NG_PLANT_CODE_UNIQUE` UNIQUE(`PLANT_ID`,`CODE`)
);
--> statement-breakpoint
CREATE TABLE `TT_INSPECTION_H` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`LINE_ID` bigint unsigned,
	`MACHINE_ID` bigint unsigned,
	`PROCESS_TYPE` enum('CASTING','MACHINING','ASSEMBLING','INJECTION') NOT NULL,
	`INSPECTED_AT` timestamp NOT NULL,
	`SHIFT` enum('1','2','3'),
	`CHECKED_QTY` int NOT NULL DEFAULT 0,
	`OK_QTY` int NOT NULL DEFAULT 0,
	`NG_QTY` int NOT NULL DEFAULT 0,
	`INSPECTOR_ID` bigint unsigned,
	`NOTE` varchar(255),
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_INSPECTION_H_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_DELIVERY` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`CUSTOMER_ID` bigint unsigned NOT NULL,
	`DOCUMENT_NUMBER` varchar(64) NOT NULL,
	`MANIFEST_NUMBER` varchar(64),
	`PDS_NUMBER` varchar(64),
	`DELIVERY_DATE` date NOT NULL,
	`CYCLE` int NOT NULL DEFAULT 1,
	`DOCK` varchar(32),
	`PLAN_TIME` time,
	`DEPARTED_AT` timestamp,
	`ARRIVED_AT` timestamp,
	`STATUS` enum('DRAFT','PICKING','PICKED','LOADING','SHIPPED','RECEIVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`LOCATION_ID` bigint unsigned,
	`STAGING_LOCATION_ID` bigint unsigned,
	`TRUCK_NUMBER` varchar(32),
	`DRIVER_NAME` varchar(128),
	`TRUCK_STATUS` enum('PENDING','ARRIVED','LOADING','DEPARTED') NOT NULL DEFAULT 'PENDING',
	`TRUCK_PICKED_AT` timestamp,
	`TRUCK_PICKED_BY_ID` bigint unsigned,
	`CREATED_BY_ID` bigint unsigned,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_DELIVERY_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_DELIVERY_PLANT_DOCUMENT_UNIQUE` UNIQUE(`PLANT_ID`,`DOCUMENT_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TT_DELIVERY_ITEM` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`DELIVERY_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`CUSTOMER_PART_ID` bigint unsigned,
	`PLANNED_KANBAN` int NOT NULL DEFAULT 0,
	`PLANNED_QTY` int NOT NULL DEFAULT 0,
	`QTY_PER_KANBAN` int NOT NULL DEFAULT 0,
	`PICKED_KANBAN` int NOT NULL DEFAULT 0,
	`PICKED_QTY` int NOT NULL DEFAULT 0,
	`ACTUAL_KANBAN` int NOT NULL DEFAULT 0,
	`ACTUAL_QTY` int NOT NULL DEFAULT 0,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_DELIVERY_ITEM_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_DELIVERY_ITEM_UNIQUE` UNIQUE(`DELIVERY_ID`,`PART_ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_MACHINE_EVENT` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`MACHINE_ID` bigint unsigned,
	`TYPE` enum('SHOT','CYCLE_END','ALARM','DOWNTIME_START','DOWNTIME_END','STATUS_CHANGE','DANDORI_START','DANDORI_END') NOT NULL,
	`SOURCE` enum('MQTT','J922_SYNC','MANUAL') NOT NULL,
	`STATUS` varchar(64),
	`SHOT_COUNT` int,
	`OCCURRED_AT` timestamp NOT NULL,
	`DEDUPE_KEY` varchar(128),
	`PAYLOAD` json,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_MACHINE_EVENT_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_BOM` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`PARENT_PART_ID` bigint unsigned NOT NULL,
	`COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`QTY_PER` decimal(12,4) NOT NULL,
	`UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`SCRAP_PCT` decimal(5,2) NOT NULL DEFAULT '0',
	`SEQUENCE` int NOT NULL DEFAULT 0,
	`EFFECTIVE_FROM` date NOT NULL,
	`EFFECTIVE_TO` date,
	`NOTE` varchar(255),
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_BOM_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_CONSUMPTION` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`LINE_ID` bigint unsigned,
	`PRODUCED_PART_ID` bigint unsigned NOT NULL,
	`COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`LOT_ID` bigint unsigned,
	`QTY` decimal(14,4) NOT NULL,
	`UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`SOURCE` enum('BACKFLUSH','MANUAL','ADJUSTMENT') NOT NULL,
	`OCCURRED_AT` timestamp NOT NULL,
	`USER_ID` bigint unsigned,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_CONSUMPTION_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_GENEALOGY` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`PARENT_SERIAL` varchar(64) NOT NULL,
	`PARENT_PART_ID` bigint unsigned NOT NULL,
	`COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`COMPONENT_SERIAL` varchar(64),
	`COMPONENT_LOT_ID` bigint unsigned,
	`QTY` decimal(14,4) NOT NULL DEFAULT '1',
	`EVIDENCE` enum('SCANNED','INFERRED') NOT NULL DEFAULT 'INFERRED',
	`OCCURRED_AT` timestamp NOT NULL,
	`SUPERSEDED_AT` timestamp,
	`SUPERSEDED_BY_REPAIR_ID` bigint unsigned,
	`META` json,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `TT_GENEALOGY_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_LOT` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`LOT_NUMBER` varchar(64) NOT NULL,
	`SUPPLIER_LOT_NUMBER` varchar(64),
	`SUPPLIER_ID` bigint unsigned,
	`RECEIVED_AT` timestamp,
	`EXPIRES_AT` date,
	`INITIAL_QTY` decimal(14,4) NOT NULL DEFAULT '0',
	`STATUS` enum('OPEN','CONSUMED','BLOCKED','RETURNED') NOT NULL DEFAULT 'OPEN',
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_LOT_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_LOT_PLANT_NUMBER_UNIQUE` UNIQUE(`PLANT_ID`,`LOT_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TT_PURCHASE_RECEIPT_L` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`RECEIPT_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`LOT_ID` bigint unsigned,
	`QTY` decimal(14,4) NOT NULL,
	`UOM` varchar(16) NOT NULL DEFAULT 'pcs',
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_PURCHASE_RECEIPT_L_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_PURCHASE_RECEIPT_H` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`SUPPLIER_ID` bigint unsigned NOT NULL,
	`DOCUMENT_NUMBER` varchar(64) NOT NULL,
	`SUPPLIER_DOC_NUMBER` varchar(64),
	`RECEIVED_AT` timestamp NOT NULL,
	`LOCATION_ID` bigint unsigned,
	`STATUS` enum('DRAFT','RECEIVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`RECEIVED_BY_ID` bigint unsigned,
	`NOTE` varchar(255),
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_PURCHASE_RECEIPT_H_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_PURCHASE_RECEIPT_H_PLANT_DOCUMENT_UNIQUE` UNIQUE(`PLANT_ID`,`DOCUMENT_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TT_GOODS_MOVEMENT_L` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`TRANSFER_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`LOT_ID` bigint unsigned,
	`SERIAL_NUMBER` varchar(64),
	`QTY` decimal(14,4) NOT NULL,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_GOODS_MOVEMENT_L_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_GOODS_MOVEMENT_H` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`DOCUMENT_NUMBER` varchar(64) NOT NULL,
	`FROM_LOCATION_ID` bigint unsigned,
	`TO_LOCATION_ID` bigint unsigned,
	`FROM_LINE_ID` bigint unsigned,
	`TO_LINE_ID` bigint unsigned,
	`MOVED_AT` timestamp NOT NULL,
	`STATUS` enum('DRAFT','MOVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
	`USER_ID` bigint unsigned,
	`NOTE` varchar(255),
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_GOODS_MOVEMENT_H_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_GOODS_MOVEMENT_H_PLANT_DOCUMENT_UNIQUE` UNIQUE(`PLANT_ID`,`DOCUMENT_NUMBER`)
);
--> statement-breakpoint
CREATE TABLE `TT_NG_DISPOSITION` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`LINE_ID` bigint unsigned,
	`PART_ID` bigint unsigned NOT NULL,
	`SERIAL_NUMBER` varchar(64),
	`LOT_ID` bigint unsigned,
	`QTY` decimal(14,4) NOT NULL,
	`DISPOSITION` enum('REMELT','REPAIR','DISCARD','RETURN_SUPPLIER') NOT NULL,
	`CONVERTED_TO_PART_ID` bigint unsigned,
	`CONVERTED_QTY` decimal(14,4),
	`CONVERTED_LOT_ID` bigint unsigned,
	`REASON` varchar(255),
	`OCCURRED_AT` timestamp NOT NULL,
	`USER_ID` bigint unsigned,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_NG_DISPOSITION_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_REPAIR_L` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`REPAIR_ID` bigint unsigned NOT NULL,
	`COMPONENT_PART_ID` bigint unsigned NOT NULL,
	`REMOVED_SERIAL` varchar(64),
	`REMOVED_LOT_ID` bigint unsigned,
	`REMOVED_DISPOSITION` enum('REMELT','REPAIR','DISCARD','RETURN_SUPPLIER'),
	`INSTALLED_SERIAL` varchar(64),
	`INSTALLED_LOT_ID` bigint unsigned,
	`QTY` decimal(14,4) NOT NULL DEFAULT '1',
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_REPAIR_L_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TT_REPAIR_H` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`LINE_ID` bigint unsigned,
	`PART_ID` bigint unsigned NOT NULL,
	`SERIAL_NUMBER` varchar(64) NOT NULL,
	`REASON` varchar(255),
	`STATUS` enum('OPEN','DONE','SCRAPPED') NOT NULL DEFAULT 'OPEN',
	`STARTED_AT` timestamp NOT NULL,
	`FINISHED_AT` timestamp,
	`USER_ID` bigint unsigned,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_REPAIR_H_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_SCRAP_RULE` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`PART_ID` bigint unsigned NOT NULL,
	`DISPOSITION` enum('REMELT','REPAIR','DISCARD','RETURN_SUPPLIER') NOT NULL,
	`CONVERTS_TO_PART_ID` bigint unsigned,
	`CONVERSION_QTY` decimal(12,4),
	`CONVERSION_UOM` varchar(16),
	`NOTE` varchar(255),
	`IS_ACTIVE` enum('0','1') NOT NULL DEFAULT '1',
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_SCRAP_RULE_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TM_SCRAP_RULE_PART_UNIQUE` UNIQUE(`PLANT_ID`,`PART_ID`)
);
--> statement-breakpoint
ALTER TABLE `TM_DEVICE` ADD CONSTRAINT `TM_DEVICE_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_USER` ADD CONSTRAINT `TM_USER_ROLE_ID_TM_ROLE_ID_fk` FOREIGN KEY (`ROLE_ID`) REFERENCES `TM_ROLE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_USER` ADD CONSTRAINT `TM_USER_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SHIPPING_PARTS` ADD CONSTRAINT `TM_SHIPPING_PARTS_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SHIPPING_PARTS` ADD CONSTRAINT `TM_SHIPPING_PARTS_CUSTOMER_ID_TM_CUST_ID_fk` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `TM_CUST`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_LINE` ADD CONSTRAINT `TM_LINE_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_MACHINE` ADD CONSTRAINT `TM_MACHINE_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_MACHINE` ADD CONSTRAINT `TM_MACHINE_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PARTS` ADD CONSTRAINT `TM_PARTS_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PARTS` ADD CONSTRAINT `TM_PARTS_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_TOOLING_PARTS` ADD CONSTRAINT `TM_TOOLING_PARTS_TOOLING_ID_TM_TOOLING_ID_fk` FOREIGN KEY (`TOOLING_ID`) REFERENCES `TM_TOOLING`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_TOOLING_PARTS` ADD CONSTRAINT `TM_TOOLING_PARTS_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_TOOLING` ADD CONSTRAINT `TM_TOOLING_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_KANBAN_ID_TM_KANBAN_ID_fk` FOREIGN KEY (`KANBAN_ID`) REFERENCES `TM_KANBAN`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_USER_ID_TM_USER_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` ADD CONSTRAINT `TT_KANBAN_EVENT_DEVICE_ID_TM_DEVICE_ID_fk` FOREIGN KEY (`DEVICE_ID`) REFERENCES `TM_DEVICE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_KANBAN` ADD CONSTRAINT `TM_KANBAN_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_KANBAN` ADD CONSTRAINT `TM_KANBAN_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_KANBAN` ADD CONSTRAINT `TM_KANBAN_CUSTOMER_ID_TM_CUST_ID_fk` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `TM_CUST`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PRODUCTION_PLAN` ADD CONSTRAINT `TT_PRODUCTION_PLAN_CUSTOMER_ID_TM_CUST_ID_fk` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `TM_CUST`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_MACHINE_ID_TM_MACHINE_ID_fk` FOREIGN KEY (`MACHINE_ID`) REFERENCES `TM_MACHINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_PRODUCTION_PLAN_ID_TT_PRODUCTION_PLAN_ID_fk` FOREIGN KEY (`PRODUCTION_PLAN_ID`) REFERENCES `TT_PRODUCTION_PLAN`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_USER_ID_TM_USER_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_HISTORY_SCAN` ADD CONSTRAINT `TT_HISTORY_SCAN_DEVICE_ID_TM_DEVICE_ID_fk` FOREIGN KEY (`DEVICE_ID`) REFERENCES `TM_DEVICE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_LOCATION` ADD CONSTRAINT `TM_LOCATION_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_LOCATION_ID_TM_LOCATION_ID_fk` FOREIGN KEY (`LOCATION_ID`) REFERENCES `TM_LOCATION`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_MUTATION` ADD CONSTRAINT `TT_STOCK_MUTATION_USER_ID_TM_USER_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_BALANCE` ADD CONSTRAINT `TT_STOCK_BALANCE_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_STOCK_BALANCE` ADD CONSTRAINT `TT_STOCK_BALANCE_LOCATION_ID_TM_LOCATION_ID_fk` FOREIGN KEY (`LOCATION_ID`) REFERENCES `TM_LOCATION`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_L` ADD CONSTRAINT `TT_INSPECTION_L_INSPECTION_ID_TT_INSPECTION_H_ID_fk` FOREIGN KEY (`INSPECTION_ID`) REFERENCES `TT_INSPECTION_H`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_L` ADD CONSTRAINT `TT_INSPECTION_L_NG_MASTER_ID_TM_NG_ID_fk` FOREIGN KEY (`NG_MASTER_ID`) REFERENCES `TM_NG`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_NG` ADD CONSTRAINT `TM_NG_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_MACHINE_ID_TM_MACHINE_ID_fk` FOREIGN KEY (`MACHINE_ID`) REFERENCES `TM_MACHINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_INSPECTION_H` ADD CONSTRAINT `TT_INSPECTION_H_INSPECTOR_ID_TM_USER_ID_fk` FOREIGN KEY (`INSPECTOR_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_CUSTOMER_ID_TM_CUST_ID_fk` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `TM_CUST`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_LOCATION_ID_TM_LOCATION_ID_fk` FOREIGN KEY (`LOCATION_ID`) REFERENCES `TM_LOCATION`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_TRUCK_PICKED_BY_ID_TM_USER_ID_fk` FOREIGN KEY (`TRUCK_PICKED_BY_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY` ADD CONSTRAINT `TT_DELIVERY_CREATED_BY_ID_TM_USER_ID_fk` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY_ITEM` ADD CONSTRAINT `TT_DELIVERY_ITEM_DELIVERY_ID_TT_DELIVERY_ID_fk` FOREIGN KEY (`DELIVERY_ID`) REFERENCES `TT_DELIVERY`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_DELIVERY_ITEM` ADD CONSTRAINT `TT_DELIVERY_ITEM_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_MACHINE_EVENT` ADD CONSTRAINT `TT_MACHINE_EVENT_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_MACHINE_EVENT` ADD CONSTRAINT `TT_MACHINE_EVENT_MACHINE_ID_TM_MACHINE_ID_fk` FOREIGN KEY (`MACHINE_ID`) REFERENCES `TM_MACHINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_BOM` ADD CONSTRAINT `TM_BOM_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_BOM` ADD CONSTRAINT `TM_BOM_PARENT_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PARENT_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_BOM` ADD CONSTRAINT `TM_BOM_COMPONENT_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_PRODUCED_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PRODUCED_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_COMPONENT_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_CONSUMPTION` ADD CONSTRAINT `TT_CONSUMPTION_USER_ID_TM_USER_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_PARENT_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PARENT_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_COMPONENT_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GENEALOGY` ADD CONSTRAINT `TT_GENEALOGY_COMPONENT_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`COMPONENT_LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LOT` ADD CONSTRAINT `TT_LOT_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LOT` ADD CONSTRAINT `TT_LOT_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LOT` ADD CONSTRAINT `TT_LOT_SUPPLIER_ID_TM_VENDOR_ID_fk` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `TM_VENDOR`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_L` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_L_RECEIPT_ID_TT_PURCHASE_RECEIPT_H_ID_fk` FOREIGN KEY (`RECEIPT_ID`) REFERENCES `TT_PURCHASE_RECEIPT_H`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_L` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_L_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_L` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_L_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_SUPPLIER_ID_TM_VENDOR_ID_fk` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `TM_VENDOR`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_LOCATION_ID_TM_LOCATION_ID_fk` FOREIGN KEY (`LOCATION_ID`) REFERENCES `TM_LOCATION`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD CONSTRAINT `TT_PURCHASE_RECEIPT_H_RECEIVED_BY_ID_TM_USER_ID_fk` FOREIGN KEY (`RECEIVED_BY_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_L` ADD CONSTRAINT `TT_GOODS_MOVEMENT_L_TRANSFER_ID_TT_GOODS_MOVEMENT_H_ID_fk` FOREIGN KEY (`TRANSFER_ID`) REFERENCES `TT_GOODS_MOVEMENT_H`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_L` ADD CONSTRAINT `TT_GOODS_MOVEMENT_L_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_L` ADD CONSTRAINT `TT_GOODS_MOVEMENT_L_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_FROM_LOCATION_ID_TM_LOCATION_ID_fk` FOREIGN KEY (`FROM_LOCATION_ID`) REFERENCES `TM_LOCATION`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_TO_LOCATION_ID_TM_LOCATION_ID_fk` FOREIGN KEY (`TO_LOCATION_ID`) REFERENCES `TM_LOCATION`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_FROM_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`FROM_LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_TO_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`TO_LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_GOODS_MOVEMENT_H` ADD CONSTRAINT `TT_GOODS_MOVEMENT_H_USER_ID_TM_USER_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_CONVERTED_TO_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`CONVERTED_TO_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_CONVERTED_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`CONVERTED_LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG_DISPOSITION` ADD CONSTRAINT `TT_NG_DISPOSITION_USER_ID_TM_USER_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_REPAIR_ID_TT_REPAIR_H_ID_fk` FOREIGN KEY (`REPAIR_ID`) REFERENCES `TT_REPAIR_H`(`ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_COMPONENT_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`COMPONENT_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_REMOVED_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`REMOVED_LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_L` ADD CONSTRAINT `TT_REPAIR_L_INSTALLED_LOT_ID_TT_LOT_ID_fk` FOREIGN KEY (`INSTALLED_LOT_ID`) REFERENCES `TT_LOT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_LINE_ID_TM_LINE_ID_fk` FOREIGN KEY (`LINE_ID`) REFERENCES `TM_LINE`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_REPAIR_H` ADD CONSTRAINT `TT_REPAIR_H_USER_ID_TM_USER_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `TM_USER`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SCRAP_RULE` ADD CONSTRAINT `TM_SCRAP_RULE_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SCRAP_RULE` ADD CONSTRAINT `TM_SCRAP_RULE_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_SCRAP_RULE` ADD CONSTRAINT `TM_SCRAP_RULE_CONVERTS_TO_PART_ID_TM_PARTS_ID_fk` FOREIGN KEY (`CONVERTS_TO_PART_ID`) REFERENCES `TM_PARTS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `TM_DEVICE_PLANT_IDX` ON `TM_DEVICE` (`PLANT_ID`);--> statement-breakpoint
CREATE INDEX `TM_USER_PLANT_IDX` ON `TM_USER` (`PLANT_ID`);--> statement-breakpoint
CREATE INDEX `TM_SHIPPING_PARTS_PART_IDX` ON `TM_SHIPPING_PARTS` (`PART_ID`);--> statement-breakpoint
CREATE INDEX `TM_LINE_PROCESS_IDX` ON `TM_LINE` (`PROCESS_TYPE`);--> statement-breakpoint
CREATE INDEX `TM_MACHINE_EXTERNAL_REF_IDX` ON `TM_MACHINE` (`EXTERNAL_REF`);--> statement-breakpoint
CREATE INDEX `TM_PARTS_BACK_NUMBER_IDX` ON `TM_PARTS` (`BACK_NUMBER`);--> statement-breakpoint
CREATE INDEX `TM_PARTS_LINE_IDX` ON `TM_PARTS` (`LINE_ID`);--> statement-breakpoint
CREATE INDEX `TT_KANBAN_EVENT_KANBAN_IDX` ON `TT_KANBAN_EVENT` (`KANBAN_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_KANBAN_EVENT_TYPE_TIME_IDX` ON `TT_KANBAN_EVENT` (`TYPE`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TM_KANBAN_PART_STATUS_IDX` ON `TM_KANBAN` (`PART_ID`,`STATUS`);--> statement-breakpoint
CREATE INDEX `TM_KANBAN_STATUS_CREATED_IDX` ON `TM_KANBAN` (`STATUS`,`CREATED_AT`);--> statement-breakpoint
CREATE INDEX `TT_PRODUCTION_PLAN_DATE_LINE_IDX` ON `TT_PRODUCTION_PLAN` (`PLAN_DATE`,`LINE_ID`);--> statement-breakpoint
CREATE INDEX `TT_PRODUCTION_PLAN_PART_DATE_IDX` ON `TT_PRODUCTION_PLAN` (`PART_ID`,`PLAN_DATE`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_TIME_IDX` ON `TT_HISTORY_SCAN` (`SCANNED_AT`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_LINE_KIND_TIME_IDX` ON `TT_HISTORY_SCAN` (`LINE_ID`,`KIND`,`SCANNED_AT`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_PART_TIME_IDX` ON `TT_HISTORY_SCAN` (`PART_ID`,`SCANNED_AT`);--> statement-breakpoint
CREATE INDEX `TT_HISTORY_SCAN_SERIAL_IDX` ON `TT_HISTORY_SCAN` (`SERIAL_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_PART_TIME_IDX` ON `TT_STOCK_MUTATION` (`PART_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_TYPE_TIME_IDX` ON `TT_STOCK_MUTATION` (`TYPE`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_SOURCE_IDX` ON `TT_STOCK_MUTATION` (`SOURCE_TABLE`,`SOURCE_ID`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_MUTATION_LOT_IDX` ON `TT_STOCK_MUTATION` (`LOT_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_STOCK_BALANCE_DATE_IDX` ON `TT_STOCK_BALANCE` (`BALANCE_DATE`);--> statement-breakpoint
CREATE INDEX `TT_INSPECTION_L_INSPECTION_IDX` ON `TT_INSPECTION_L` (`INSPECTION_ID`);--> statement-breakpoint
CREATE INDEX `TT_INSPECTION_H_PART_TIME_IDX` ON `TT_INSPECTION_H` (`PART_ID`,`INSPECTED_AT`);--> statement-breakpoint
CREATE INDEX `TT_INSPECTION_H_LINE_TIME_IDX` ON `TT_INSPECTION_H` (`LINE_ID`,`INSPECTED_AT`);--> statement-breakpoint
CREATE INDEX `TT_DELIVERY_DATE_CUSTOMER_IDX` ON `TT_DELIVERY` (`DELIVERY_DATE`,`CUSTOMER_ID`);--> statement-breakpoint
CREATE INDEX `TT_DELIVERY_STATUS_IDX` ON `TT_DELIVERY` (`STATUS`);--> statement-breakpoint
CREATE INDEX `TT_DELIVERY_ITEM_PART_IDX` ON `TT_DELIVERY_ITEM` (`PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_MACHINE_EVENT_MACHINE_TIME_IDX` ON `TT_MACHINE_EVENT` (`MACHINE_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_MACHINE_EVENT_TYPE_TIME_IDX` ON `TT_MACHINE_EVENT` (`TYPE`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_MACHINE_EVENT_DEDUPE_IDX` ON `TT_MACHINE_EVENT` (`DEDUPE_KEY`);--> statement-breakpoint
CREATE INDEX `TM_BOM_PARENT_IDX` ON `TM_BOM` (`PARENT_PART_ID`,`EFFECTIVE_FROM`);--> statement-breakpoint
CREATE INDEX `TM_BOM_COMPONENT_IDX` ON `TM_BOM` (`COMPONENT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_CONSUMPTION_PRODUCED_IDX` ON `TT_CONSUMPTION` (`PRODUCED_PART_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_CONSUMPTION_COMPONENT_IDX` ON `TT_CONSUMPTION` (`COMPONENT_PART_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_CONSUMPTION_LOT_IDX` ON `TT_CONSUMPTION` (`LOT_ID`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_PARENT_IDX` ON `TT_GENEALOGY` (`PARENT_SERIAL`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_LOT_IDX` ON `TT_GENEALOGY` (`COMPONENT_LOT_ID`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_COMPONENT_SERIAL_IDX` ON `TT_GENEALOGY` (`COMPONENT_SERIAL`);--> statement-breakpoint
CREATE INDEX `TT_GENEALOGY_PART_TIME_IDX` ON `TT_GENEALOGY` (`PARENT_PART_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_LOT_PART_IDX` ON `TT_LOT` (`PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_LOT_SUPPLIER_LOT_IDX` ON `TT_LOT` (`SUPPLIER_LOT_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_PURCHASE_RECEIPT_L_RECEIPT_IDX` ON `TT_PURCHASE_RECEIPT_L` (`RECEIPT_ID`);--> statement-breakpoint
CREATE INDEX `TT_PURCHASE_RECEIPT_L_PART_IDX` ON `TT_PURCHASE_RECEIPT_L` (`PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_PURCHASE_RECEIPT_H_SUPPLIER_DATE_IDX` ON `TT_PURCHASE_RECEIPT_H` (`SUPPLIER_ID`,`RECEIVED_AT`);--> statement-breakpoint
CREATE INDEX `TT_GOODS_MOVEMENT_L_TRANSFER_IDX` ON `TT_GOODS_MOVEMENT_L` (`TRANSFER_ID`);--> statement-breakpoint
CREATE INDEX `TT_GOODS_MOVEMENT_L_PART_IDX` ON `TT_GOODS_MOVEMENT_L` (`PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_GOODS_MOVEMENT_H_MOVED_IDX` ON `TT_GOODS_MOVEMENT_H` (`MOVED_AT`);--> statement-breakpoint
CREATE INDEX `TT_NG_DISPOSITION_PART_TIME_IDX` ON `TT_NG_DISPOSITION` (`PART_ID`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_NG_DISPOSITION_SERIAL_IDX` ON `TT_NG_DISPOSITION` (`SERIAL_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_NG_DISPOSITION_DISPOSITION_IDX` ON `TT_NG_DISPOSITION` (`DISPOSITION`,`OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_L_REPAIR_IDX` ON `TT_REPAIR_L` (`REPAIR_ID`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_L_COMPONENT_IDX` ON `TT_REPAIR_L` (`COMPONENT_PART_ID`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_H_SERIAL_IDX` ON `TT_REPAIR_H` (`SERIAL_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_REPAIR_H_STATUS_IDX` ON `TT_REPAIR_H` (`STATUS`,`STARTED_AT`);