CREATE TABLE `TT_SAP_OUTBOX` (
	`ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`PLANT_ID` bigint unsigned NOT NULL,
	`SOURCE_TABLE` varchar(64) NOT NULL,
	`SOURCE_ID` bigint unsigned NOT NULL,
	`DOC_TYPE` varchar(32) NOT NULL,
	`MOVEMENT_TYPE` varchar(8),
	`IDEMPOTENCY_KEY` varchar(128) NOT NULL,
	`PAYLOAD` json NOT NULL,
	`STATUS` enum('PENDING','SENT','FAILED','HELD','SKIPPED') NOT NULL DEFAULT 'PENDING',
	`ATTEMPTS` int NOT NULL DEFAULT 0,
	`LAST_ERROR` varchar(1000),
	`SAP_DOC_NUMBER` varchar(32),
	`OCCURRED_AT` timestamp NOT NULL,
	`SENT_AT` timestamp,
	`CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_SAP_OUTBOX_ID` PRIMARY KEY(`ID`),
	CONSTRAINT `TT_SAP_OUTBOX_SOURCE_UNIQUE` UNIQUE(`SOURCE_TABLE`,`SOURCE_ID`),
	CONSTRAINT `TT_SAP_OUTBOX_IDEMPOTENCY_UNIQUE` UNIQUE(`IDEMPOTENCY_KEY`)
);
--> statement-breakpoint
ALTER TABLE `TT_SAP_OUTBOX` ADD CONSTRAINT `TT_SAP_OUTBOX_PLANT_ID_TM_PLANT_ID_fk` FOREIGN KEY (`PLANT_ID`) REFERENCES `TM_PLANT`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `TT_SAP_OUTBOX_STATUS_IDX` ON `TT_SAP_OUTBOX` (`STATUS`,`OCCURRED_AT`);