CREATE TABLE `TM_PROGRAM_NUMBER` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_CODE` varchar(4) NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`CHR_PRODUCT` varchar(64),
	`INT_CUSTOMER_ID` bigint unsigned,
	`FLG_IS_ASSY` boolean NOT NULL DEFAULT false,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_PROGRAM_NUMBER_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_PROGRAM_NUMBER_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
ALTER TABLE `TM_PROGRAM_NUMBER` ADD CONSTRAINT `TM_PROGRAM_NUMBER_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PROGRAM_NUMBER` ADD CONSTRAINT `TM_PROGRAM_NUMBER_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PROGRAM_NUMBER` ADD CONSTRAINT `TM_PROGRAM_NUMBER_INT_CUSTOMER_ID_TM_CUST_INT_ID_fk` FOREIGN KEY (`INT_CUSTOMER_ID`) REFERENCES `TM_CUST`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `TM_PROGRAM_NUMBER_PART_IDX` ON `TM_PROGRAM_NUMBER` (`INT_PART_ID`);