CREATE TABLE `TT_NG` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING_WIP','CASTING_FG','MACHINING_WIP','MACHINING_FG','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY'),
	`INT_NG_MASTER_ID` bigint unsigned NOT NULL,
	`CHR_ORIGIN` enum('INLINE','OUTLINE') NOT NULL,
	`CHR_SOURCE` enum('PART_CODE','KANBAN') NOT NULL,
	`CHR_RAW_CODE` varchar(255) NOT NULL,
	`CHR_SERIAL_NUMBER` varchar(64),
	`INT_KANBAN_ID` bigint unsigned,
	`INT_SCAN_EVENT_ID` bigint unsigned,
	`INT_QTY` int NOT NULL DEFAULT 1,
	`DTM_OCCURRED_AT` timestamp NOT NULL,
	`CHR_NPK` varchar(32),
	`INT_USER_ID` bigint unsigned,
	`DTM_CANCELLED_AT` timestamp,
	`INT_CANCELLED_BY_ID` bigint unsigned,
	`CHR_CANCEL_REASON` varchar(255),
	`CHR_ACTIVE_KEY` varchar(320),
	`CHR_META` json,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_NG_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_NG_ACTIVE_UNIQUE` UNIQUE(`CHR_ACTIVE_KEY`)
);
--> statement-breakpoint
ALTER TABLE `TT_KANBAN_EVENT` MODIFY COLUMN `CHR_TYPE` enum('PRODUCED','PULLED','PAIRED','STORED','LOADED','DELIVERED','CANCELLED','ADJUSTED','VOIDED') NOT NULL;--> statement-breakpoint
ALTER TABLE `TM_NG` ADD `CHR_PROCESS_GROUP` enum('MELTING','CASTING','MACHINING','ASSEMBLING','INJECTION','PAINTING','DELIVERY');--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_NG_MASTER_ID_TM_NG_INT_ID_fk` FOREIGN KEY (`INT_NG_MASTER_ID`) REFERENCES `TM_NG`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_KANBAN_ID_TM_KANBAN_INT_ID_fk` FOREIGN KEY (`INT_KANBAN_ID`) REFERENCES `TM_KANBAN`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_SCAN_EVENT_ID_TT_HISTORY_SCAN_INT_ID_fk` FOREIGN KEY (`INT_SCAN_EVENT_ID`) REFERENCES `TT_HISTORY_SCAN`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_NG` ADD CONSTRAINT `TT_NG_INT_CANCELLED_BY_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_CANCELLED_BY_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `TT_NG_PART_TIME_IDX` ON `TT_NG` (`INT_PART_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_NG_MASTER_TIME_IDX` ON `TT_NG` (`INT_NG_MASTER_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_NG_LINE_TIME_IDX` ON `TT_NG` (`INT_LINE_ID`,`DTM_OCCURRED_AT`);--> statement-breakpoint
CREATE INDEX `TT_NG_SERIAL_IDX` ON `TT_NG` (`CHR_SERIAL_NUMBER`);--> statement-breakpoint
CREATE INDEX `TT_NG_KANBAN_IDX` ON `TT_NG` (`INT_KANBAN_ID`);--> statement-breakpoint
CREATE INDEX `TM_NG_GROUP_IDX` ON `TM_NG` (`INT_PLANT_ID`,`CHR_PROCESS_GROUP`,`INT_SORT_ORDER`);