CREATE TABLE `TM_MENU` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`CHR_KEY` varchar(64) NOT NULL,
	`CHR_LABEL` varchar(128) NOT NULL,
	`CHR_HREF` varchar(191) NOT NULL,
	`CHR_ICON` varchar(64) NOT NULL,
	`CHR_MENU_GROUP` enum('Produksi','Logistik','Integrasi','Master Data','Administrasi') NOT NULL,
	`INT_SORT_ORDER` int NOT NULL DEFAULT 0,
	`FLG_ADMIN_ONLY` boolean NOT NULL DEFAULT false,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_MENU_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_MENU_KEY_UNIQUE` UNIQUE(`CHR_KEY`)
);
--> statement-breakpoint
CREATE TABLE `TM_ROLE_MENU` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_ROLE_ID` bigint unsigned NOT NULL,
	`INT_MENU_ID` bigint unsigned NOT NULL,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_ROLE_MENU_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_ROLE_MENU_UNIQUE` UNIQUE(`INT_ROLE_ID`,`INT_MENU_ID`)
);
--> statement-breakpoint
ALTER TABLE `TM_ROLE` ADD `FLG_IS_ACTIVE` boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE `TM_ROLE_MENU` ADD CONSTRAINT `TM_ROLE_MENU_INT_ROLE_ID_TM_ROLE_INT_ID_fk` FOREIGN KEY (`INT_ROLE_ID`) REFERENCES `TM_ROLE`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_ROLE_MENU` ADD CONSTRAINT `TM_ROLE_MENU_INT_MENU_ID_TM_MENU_INT_ID_fk` FOREIGN KEY (`INT_MENU_ID`) REFERENCES `TM_MENU`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `TM_MENU_GROUP_IDX` ON `TM_MENU` (`CHR_MENU_GROUP`,`INT_SORT_ORDER`);--> statement-breakpoint
CREATE INDEX `TM_ROLE_MENU_ROLE_IDX` ON `TM_ROLE_MENU` (`INT_ROLE_ID`);