CREATE TABLE `TM_ROUTE_PROCESS` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_PROCESS_TYPE` enum('MELTING','CASTING_WIP','CASTING_FG','MACHINING_WIP','MACHINING_FG','ASSEMBLING_UNIT','INJECTION','PAINTING','ASSEMBLING_BODY','DELIVERY') NOT NULL,
	`INT_INPUT_LOCATION_ID` bigint unsigned,
	`INT_OUTPUT_LOCATION_ID` bigint unsigned,
	`INT_TRANSFER_LOCATION_ID` bigint unsigned,
	`FLG_SAP_PRODUCTION_ENABLED` boolean NOT NULL DEFAULT false,
	`FLG_SAP_TRANSFER_ENABLED` boolean NOT NULL DEFAULT false,
	`CHR_SAP_TRANSFER_MVT` varchar(3),
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_ROUTE_PROCESS_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_ROUTE_PROCESS_PLANT_PROCESS_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_PROCESS_TYPE`)
);
--> statement-breakpoint
ALTER TABLE `TM_ROUTE_PROCESS` ADD CONSTRAINT `TM_ROUTE_PROCESS_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` DROP COLUMN `INT_INPUT_LOCATION_ID`;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` DROP COLUMN `INT_OUTPUT_LOCATION_ID`;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` DROP COLUMN `INT_TRANSFER_LOCATION_ID`;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` DROP COLUMN `FLG_SAP_PRODUCTION_ENABLED`;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` DROP COLUMN `FLG_SAP_TRANSFER_ENABLED`;--> statement-breakpoint
ALTER TABLE `TM_PROCESS_PARTS` DROP COLUMN `CHR_SAP_TRANSFER_MVT`;