CREATE TABLE `TM_KANBAN_CROP_PROFILE` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_CUSTOMER_ID` bigint unsigned NOT NULL,
	`INT_WIDTH_TENTHS` int NOT NULL DEFAULT 900,
	`INT_HEIGHT_TENTHS` int NOT NULL DEFAULT 620,
	`INT_OFFSET_X_TENTHS` int NOT NULL DEFAULT 80,
	`INT_OFFSET_Y_TENTHS` int NOT NULL DEFAULT 80,
	`INT_GAP_X_TENTHS` int NOT NULL DEFAULT 40,
	`INT_GAP_Y_TENTHS` int NOT NULL DEFAULT 40,
	`INT_COLUMNS` int NOT NULL DEFAULT 2,
	`INT_ROWS` int NOT NULL DEFAULT 4,
	`INT_UPDATED_BY_ID` bigint unsigned,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_KANBAN_CROP_PROFILE_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_KANBAN_CROP_PROFILE_CUSTOMER_UNIQUE` UNIQUE(`INT_CUSTOMER_ID`)
);
--> statement-breakpoint
ALTER TABLE `TM_KANBAN_CROP_PROFILE` ADD CONSTRAINT `TM_KANBAN_CROP_PROFILE_INT_CUSTOMER_ID_TM_CUST_INT_ID_fk` FOREIGN KEY (`INT_CUSTOMER_ID`) REFERENCES `TM_CUST`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_KANBAN_CROP_PROFILE` ADD CONSTRAINT `TM_KANBAN_CROP_PROFILE_INT_UPDATED_BY_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_UPDATED_BY_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;