CREATE TABLE `TT_LINE_STOP` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned NOT NULL,
	`INT_PART_ID` bigint unsigned,
	`INT_STOP_REASON_ID` bigint unsigned,
	`DTM_PRODUCTION_DATE` date NOT NULL,
	`DTM_STARTED_AT` timestamp NOT NULL,
	`DTM_ENDED_AT` timestamp,
	`CHR_CLOSED_BY` enum('TOMBOL','SCAN','SISTEM'),
	`CHR_NPK` varchar(32),
	`INT_USER_ID` bigint unsigned,
	`CHR_NOTE` varchar(255),
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TT_LINE_STOP_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_STOP_REASON` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`INT_LINE_ID` bigint unsigned,
	`CHR_CODE` varchar(32) NOT NULL,
	`CHR_NAME` varchar(128) NOT NULL,
	`CHR_CATEGORY` enum('PROBLEM','SETUP','QC','CHANGEOVER','MATERIAL','LAINNYA') NOT NULL DEFAULT 'PROBLEM',
	`FLG_IS_PLANNED` boolean NOT NULL DEFAULT false,
	`INT_SORT_ORDER` int NOT NULL DEFAULT 0,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_STOP_REASON_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_STOP_REASON_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
CREATE TABLE `TM_WORK_BREAK` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_WORK_TIME_ID` bigint unsigned NOT NULL,
	`CHR_NAME` varchar(64) NOT NULL,
	`DTM_START_TIME` time NOT NULL,
	`DTM_END_TIME` time NOT NULL,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_WORK_BREAK_INT_ID` PRIMARY KEY(`INT_ID`)
);
--> statement-breakpoint
CREATE TABLE `TM_WORK_TIME` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`INT_PLANT_ID` bigint unsigned NOT NULL,
	`CHR_CODE` varchar(16) NOT NULL,
	`CHR_NAME` varchar(64) NOT NULL,
	`DTM_START_TIME` time NOT NULL,
	`DTM_END_TIME` time NOT NULL,
	`FLG_STARTS_PRODUCTION_DAY` boolean NOT NULL DEFAULT false,
	`FLG_IS_ACTIVE` boolean NOT NULL DEFAULT true,
	`DTM_CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTM_UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `TM_WORK_TIME_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TM_WORK_TIME_PLANT_CODE_UNIQUE` UNIQUE(`INT_PLANT_ID`,`CHR_CODE`)
);
--> statement-breakpoint
ALTER TABLE `TT_LINE_STOP` ADD CONSTRAINT `TT_LINE_STOP_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LINE_STOP` ADD CONSTRAINT `TT_LINE_STOP_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LINE_STOP` ADD CONSTRAINT `TT_LINE_STOP_INT_PART_ID_TM_PARTS_INT_ID_fk` FOREIGN KEY (`INT_PART_ID`) REFERENCES `TM_PARTS`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LINE_STOP` ADD CONSTRAINT `TT_LINE_STOP_INT_STOP_REASON_ID_TM_STOP_REASON_INT_ID_fk` FOREIGN KEY (`INT_STOP_REASON_ID`) REFERENCES `TM_STOP_REASON`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TT_LINE_STOP` ADD CONSTRAINT `TT_LINE_STOP_INT_USER_ID_TM_USER_INT_ID_fk` FOREIGN KEY (`INT_USER_ID`) REFERENCES `TM_USER`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_STOP_REASON` ADD CONSTRAINT `TM_STOP_REASON_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_STOP_REASON` ADD CONSTRAINT `TM_STOP_REASON_INT_LINE_ID_TM_LINE_INT_ID_fk` FOREIGN KEY (`INT_LINE_ID`) REFERENCES `TM_LINE`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_WORK_BREAK` ADD CONSTRAINT `TM_WORK_BREAK_INT_WORK_TIME_ID_TM_WORK_TIME_INT_ID_fk` FOREIGN KEY (`INT_WORK_TIME_ID`) REFERENCES `TM_WORK_TIME`(`INT_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TM_WORK_TIME` ADD CONSTRAINT `TM_WORK_TIME_INT_PLANT_ID_TM_PLANT_INT_ID_fk` FOREIGN KEY (`INT_PLANT_ID`) REFERENCES `TM_PLANT`(`INT_ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `TT_LINE_STOP_LINE_TIME_IDX` ON `TT_LINE_STOP` (`INT_LINE_ID`,`DTM_STARTED_AT`);--> statement-breakpoint
CREATE INDEX `TT_LINE_STOP_DATE_IDX` ON `TT_LINE_STOP` (`DTM_PRODUCTION_DATE`,`INT_LINE_ID`);--> statement-breakpoint
CREATE INDEX `TT_LINE_STOP_OPEN_IDX` ON `TT_LINE_STOP` (`INT_LINE_ID`,`DTM_ENDED_AT`);--> statement-breakpoint
CREATE INDEX `TM_STOP_REASON_LINE_IDX` ON `TM_STOP_REASON` (`INT_LINE_ID`,`FLG_IS_ACTIVE`);--> statement-breakpoint
CREATE INDEX `TM_WORK_BREAK_SHIFT_IDX` ON `TM_WORK_BREAK` (`INT_WORK_TIME_ID`);