CREATE TABLE `TT_DELIVERY_SYNC` (
	`INT_ID` bigint unsigned AUTO_INCREMENT NOT NULL,
	`DTM_OPERATIONAL_DATE` date NOT NULL,
	`DTM_SYNCED_AT` timestamp NOT NULL,
	`CHR_RESULT` json NOT NULL,
	CONSTRAINT `TT_DELIVERY_SYNC_INT_ID` PRIMARY KEY(`INT_ID`),
	CONSTRAINT `TT_DELIVERY_SYNC_DATE_UNIQUE` UNIQUE(`DTM_OPERATIONAL_DATE`)
);
--> statement-breakpoint
ALTER TABLE `TT_DELIVERY_ITEM` ADD `CHR_CUST_PART_NO` varchar(64);