ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD `INT_ARES_ORDER_ID` bigint unsigned;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD `CHR_SOURCE_SNAPSHOT` json;--> statement-breakpoint
ALTER TABLE `TT_PURCHASE_RECEIPT_H` ADD `DTM_CLOSED_AT` timestamp;--> statement-breakpoint
CREATE INDEX `TT_PURCHASE_RECEIPT_H_ARES_IDX` ON `TT_PURCHASE_RECEIPT_H` (`INT_ARES_ORDER_ID`,`CHR_STATUS`);